export { default as NTbody } from './tbody.vue'
export { default as NTfoot } from './tfoot.vue'
export { default as NThead } from './thead.vue'
export { default as NTable } from './index.vue'
export { default as NTr } from './tr.vue'
